using System.Text.Json;
using System;
using Microsoft.SemanticKernel;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Humanizer.Configuration;

namespace GenAICreateQuestionsFromParagraphs
{
    internal class Program
    {
        private const string DBPEDIASQUESTIONSDIRECTORY = @"DbPediaQuestions";

        static async Task Main(string[] args)
        {
            Console.Title = "GenAI - Create & Answer Questions From DbPedia";

            var asciiArt = 
                """
                ,-----.                    ,--.             ,---.          ,---.                                         
                '  .--.,--.--.,---. ,--,--,-'  '-.,---.     |  o ,-.       /  O  \,--,--, ,---.,--.   ,--.,---.,--.--.    
                |  |   |  .--| .-. ' ,-.  '-.  .-| .-. :    .'     /_     |  .-.  |      (  .-'|  |.'.|  | .-. |  .--'    
                '  '--'|  |  \   --\ '-'  | |  | \   --.    |  o  .__)    |  | |  |  ||  .-'  `|   .'.   \   --|  |       
                ,-----.--'   `----'`--`--' `-,--.`,--.'     `---'        `--' `--`--''--`----''--'   '--'`----`--'       
                '  .-.  ' ,--.,--.,---. ,---,-'  '-`--',---.,--,--, ,---.                                                 
                |  | |  | |  ||  | .-. (  .-'-.  .-,--| .-. |      (  .-'                                                 
                '  '-'  '-'  ''  \   --.-'  `)|  | |  ' '-' |  ||  .-'  `)                                                
                `-----'--'`----' `----`----' `--' `--'`---'`--''--`----'   
                """;

            Console.ForegroundColor = ConsoleColor.Yellow;
            Console.Write(asciiArt);
            ProcessingOptions selectedProcessingChoice = (ProcessingOptions)0;
            bool validInput = false;

            // Iterate until the proper input is selected by the user
            while (!validInput)
            {
                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.WriteLine(string.Empty);
                Console.WriteLine("Select one of the options, by typing either 1 through 3:");
                Console.WriteLine("1) Create questions from DbPedia titles and text");
                Console.WriteLine("2) Answer questions generated by GenAI");
                Console.WriteLine("3) Answer questions generated by GenAI (at scale)");

                var insertedText = Console.ReadLine();
                string trimmedInput = insertedText!.Trim();

                if (trimmedInput == "1" || trimmedInput == "2" || trimmedInput == "3")
                {
                    validInput = true;
                    selectedProcessingChoice = (ProcessingOptions) Int32.Parse(trimmedInput);
                }
                else
                {
                    Console.ForegroundColor = ConsoleColor.Red;
                    Console.WriteLine("Incorrect selection!!!!");
                }
            }
            Console.WriteLine("You selected: {0}", selectedProcessingChoice);


            // Set up SK
            ConfigurationBuilder configurationBuilder = new ConfigurationBuilder();
            IConfiguration configuration = configurationBuilder.AddUserSecrets<Program>().Build();
            var azureOpenAIAPIKey = configuration.GetSection("AzureOpenAI")["APIKey"];
            var azureOpenAIEndpoint = configuration.GetSection("AzureOpenAI")["Endpoint"];
            var modelDeployment = "gpt-4-0125-preview";

            var semanticKernelBuilder = Kernel.CreateBuilder();
            // Logging will be written to the debug output window
            semanticKernelBuilder.Services.AddLogging(configure => configure.AddConsole());

            semanticKernelBuilder.AddAzureOpenAIChatCompletion(
                deploymentName: modelDeployment,
                endpoint: azureOpenAIEndpoint!,
                apiKey: azureOpenAIAPIKey!
            );
            var semanticKernel = semanticKernelBuilder.Build();

            if (selectedProcessingChoice == ProcessingOptions.CreateQuestions)
            {
                Console.WriteLine("Load DbPedias");
                var dbPedias = LoadDbPedias("dbpedias.json");
                var dbPediaSampleQuestions = new List<DbPediaSampleQuestion>(100);

                var pluginsDirectory = Path.Combine(System.IO.Directory.GetCurrentDirectory(), "SemanticKernelPlugins", "QuestionPlugin");
                var createQuestionPlugin = semanticKernel.CreatePluginFromPromptDirectory(pluginsDirectory);

                foreach (var dbPedia in dbPedias)
                {
                    Console.ForegroundColor = ConsoleColor.Cyan;
                    Console.WriteLine($"Generating Question for {dbPedia.Title}");

                    var kernelFunction = createQuestionPlugin["CreateQuestion"];
                    var promptsDictionary = new Dictionary<string, object>
                    {
                        { "TITLE", dbPedia.Title },
                        { "PARAGRAPH", dbPedia.Text }
                    };

                    var kernelArguments = new KernelArguments(promptsDictionary!);

                    var generatedQuestion = await semanticKernel.InvokeAsync(kernelFunction, kernelArguments);

                    var sampleQuestion = new DbPediaSampleQuestion
                    {
                        Id = dbPedia.Id,
                        Title = dbPedia.Title,
                        Text = dbPedia.Text,
                        SampleQuestion = generatedQuestion.GetValue<string>() ?? string.Empty
                    };

                    dbPediaSampleQuestions.Add(sampleQuestion);
                    Task.Delay(250).Wait();
                }

                Console.WriteLine("Save DbPedias with Sample Questions");
                var dbPediaSampleQuestionsJson = JsonSerializer.Serialize(dbPediaSampleQuestions);
                File.WriteAllText(("dbPediasSampleQuestions.json"), dbPediaSampleQuestionsJson);
            }
            else if(selectedProcessingChoice == ProcessingOptions.AnswerQuestions)
            {
                var dbPediaQuestions = LoadDbPediaQuestions(Path.Combine(DBPEDIASQUESTIONSDIRECTORY, "dbPediasSampleQuestions.json"));

                var pluginsDirectory = Path.Combine(System.IO.Directory.GetCurrentDirectory(), "SemanticKernelPlugins", "QuestionPlugin");
                var createQuestionPlugin = semanticKernel.CreatePluginFromPromptDirectory(pluginsDirectory);

                Parallel.ForEach(dbPediaQuestions, dbPediaQuestion =>
                {
                    Console.ForegroundColor = ConsoleColor.Cyan;
                    Console.WriteLine($"Generating ANSWER for {dbPediaQuestion.SampleQuestion}");

                    var kernelFunction = createQuestionPlugin["AnswerQuestion"];
                    var promptsDictionary = new Dictionary<string, object>
                    {
                        { "TITLE", dbPediaQuestion.Title },
                        { "PARAGRAPH", dbPediaQuestion.Text },
                        { "QUESTION", dbPediaQuestion.SampleQuestion }
                    };

                    var kernelArguments = new KernelArguments(promptsDictionary!);

                    var generatedQuestion = semanticKernel.InvokeAsync(kernelFunction, kernelArguments).Result;
                    var generatedQuestionString = generatedQuestion.GetValue<string>() ?? string.Empty;
                    Console.WriteLine($"ANSWER: {generatedQuestionString}");
                    Console.WriteLine();

                    // Task.Delay(250).Wait();
                });

                //foreach (var dbPediaQuestion in dbPediaQuestions)
                //{
                //    Console.ForegroundColor = ConsoleColor.Cyan;
                //    Console.WriteLine($"Generating ANSWER for {dbPediaQuestion.SampleQuestion}");

                //    var kernelFunction = createQuestionPlugin["AnswerQuestion"];
                //    var promptsDictionary = new Dictionary<string, object>
                //    {
                //        { "TITLE", dbPediaQuestion.Title },
                //        { "PARAGRAPH", dbPediaQuestion.Text },
                //        { "QUESTION", dbPediaQuestion.SampleQuestion }
                //    };

                //    var kernelArguments = new KernelArguments(promptsDictionary!);

                //    var generatedQuestion = await semanticKernel.InvokeAsync(kernelFunction, kernelArguments);
                //    var generatedQuestionString = generatedQuestion.GetValue<string>() ?? string.Empty;
                //    Console.WriteLine($"ANSWER: {generatedQuestionString}");
                //    Console.WriteLine();

                //    // Task.Delay(250).Wait();
                //}
            }
        }

        static List<DbPedia> LoadDbPedias(string filePath)
        {
            using (StreamReader r = new StreamReader(filePath))
            {
                string json = r.ReadToEnd();
                var dbpedias = JsonSerializer.Deserialize<List<DbPedia>>(json);
                return dbpedias;
            }
        }

        static List<DbPediaSampleQuestion> LoadDbPediaQuestions(string filePath)
        {
            using (StreamReader r = new StreamReader(filePath))
            {
                string json = r.ReadToEnd();
                var dbpedias = JsonSerializer.Deserialize<List<DbPediaSampleQuestion>>(json);
                return dbpedias;
            }
        }
    }
}
